#公共配置
server:
    port: 8088
#    程序端口
    tomcat:
      uri-encoding: UTF-8
#字符集

spring:
    #激活哪一个环境的配置文件
    profiles:
      active: dev
    #视图配置
    mvc:
      static-path-pattern: /static/**
    aop:
      proxy-target-class: true
    datasource:
        jdbc-url: jdbc:mysql://localhost:3306/houqin?useUnicode=true&characterEncoding=utf8
        username: root
        password: 102400
        driver-class-name: com.mysql.jdbc.Driver
        maximum-pool-size: 30


#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.spb.houqin.admin.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
       #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper
    refresh-mapper: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false

#日志


---
#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/houqin?useUnicode=true&characterEncoding=utf8
      username: root
      password: 102400
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30
server:
  #端口
  port: 8088
#虚拟文件上传路径
upload-path: D:/logs/houqin/


